### ISSUE TITLE
Integer quantization failing for DistilBERT trained on IMDB

### ISSUE THREAD

**Issue by sayakpaul** [sayakpaul/BERT-for-Mobile#1]
@khanhlvg

I repurposed [this notebook](https://github.com/dipanjanS/deep_transfer_learning_nlp_dhs2019/blob/master/notebooks/6%20-%20Transformers%20-%20DistilBERT.ipynb) that already shows how to train a text classification model using DistilBERT. 

The conversion went well for dynamic-range and float16 quantization but the Colab session got restarted each time I tried the integer quantization. You can find the conversion notebook [here](https://colab.research.google.com/github/sayakpaul/BERT-for-Mobile/blob/master/DistilBERT_IMDB.ipynb). You can find the model files (includes the trained weights, float16 and dynamic-range quantized TFLite models) [here](https://github.com/sayakpaul/BERT-for-Mobile/releases/tag/v0.1.0). 

**Note** that the current notebook uses the IMDB dataset for review sentiment classification. SST-2 related discussions are [here](https://github.com/sayakpaul/BERT-for-Mobile/issues/2). 

What would you suggest as the next steps? 

Benchmarking and evaluation with TFLite models are already on my mind. 

@farmaker47 @margaretmz FYI.

**Comment by khanhlvg** [comment]
Thanks Sayak!

> The conversion went well for dynamic-range and float16 quantization but the Colab session got restarted each time I tried the integer quantization.

Did the you try the conversion with tf-nightly?
From my experience with MobileBERT, integer quantization was actually quite difficult to achieve good accuracy. The TFLite team had to do quite a lot of fine tuning for the ops in MobileBERT to achieve it. As dynamic range and fp16 already work well, I think we can ignore the integer quantization.

> What would you suggest as the next steps?

I'd suggest:
* benchmarking to get latency for comparison
* calculate the accuracy to compare with other model architectures (e.g. MobileBERT)
* compare model size

**Comment by sayakpaul** [comment]
@khanhlvg 

> Did the you try the conversion with tf-nightly?

Yes, I did try it out. 

Regarding the next steps, yes, that is what I have in mind.

**Comment by sayakpaul** [comment]
@khanhlvg since the model maker example uses the SST-2 dataset, I am closing this issue. Let's continue this discussion here https://github.com/sayakpaul/BERT-for-Mobile/issues/2.
